//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosBrandBuy.Api.GeneradorDeClaves {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://stevendlavc-001-site1.atempurl.com/", ConfigurationName="GeneradorDeClaves.ServicioClaveSoap")]
    public interface ServicioClaveSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://stevendlavc-001-site1.atempurl.com/GenerarClave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiciosBrandBuy.Api.GeneradorDeClaves.Clave[] GenerarClave();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://stevendlavc-001-site1.atempurl.com/GenerarClave", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiciosBrandBuy.Api.GeneradorDeClaves.Clave[]> GenerarClaveAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stevendlavc-001-site1.atempurl.com/")]
    public partial class Clave : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string claveGeneradaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string claveGenerada {
            get {
                return this.claveGeneradaField;
            }
            set {
                this.claveGeneradaField = value;
                this.RaisePropertyChanged("claveGenerada");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioClaveSoapChannel : ServiciosBrandBuy.Api.GeneradorDeClaves.ServicioClaveSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClaveSoapClient : System.ServiceModel.ClientBase<ServiciosBrandBuy.Api.GeneradorDeClaves.ServicioClaveSoap>, ServiciosBrandBuy.Api.GeneradorDeClaves.ServicioClaveSoap {
        
        public ServicioClaveSoapClient() {
        }
        
        public ServicioClaveSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClaveSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClaveSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClaveSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiciosBrandBuy.Api.GeneradorDeClaves.Clave[] GenerarClave() {
            return base.Channel.GenerarClave();
        }
        
        public System.Threading.Tasks.Task<ServiciosBrandBuy.Api.GeneradorDeClaves.Clave[]> GenerarClaveAsync() {
            return base.Channel.GenerarClaveAsync();
        }
    }
}
